// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWLZ_95B8USoJdl3yT1K6n5UHA8N7xfPc',
    appId: '1:546122601793:web:eba5e106b154387b577dc0',
    messagingSenderId: '546122601793',
    projectId: 'dart-quiz-4ad0c',
    authDomain: 'dart-quiz-4ad0c.firebaseapp.com',
    storageBucket: 'dart-quiz-4ad0c.appspot.com',
    measurementId: 'G-L3HH025BQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbaEykgFd9WEmVFPuPed-8c3kgZBmAwoY',
    appId: '1:546122601793:android:aef381e322119399577dc0',
    messagingSenderId: '546122601793',
    projectId: 'dart-quiz-4ad0c',
    storageBucket: 'dart-quiz-4ad0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhT9974VmSaX90qs8lxCXz_Q47gGYHMxU',
    appId: '1:546122601793:ios:5c53163bcf2d5f70577dc0',
    messagingSenderId: '546122601793',
    projectId: 'dart-quiz-4ad0c',
    storageBucket: 'dart-quiz-4ad0c.appspot.com',
    iosBundleId: 'com.example.dartQuiz',
  );
}
